### ISSUE TITLE
Parsing YAML templates - Unmarshalling unknown values is not supported

### ISSUE THREAD

**Issue by alonsodomin** [hashicorp/terraform-provider-kubernetes-alpha#173]
### Terraform, Provider, Kubernetes versions
```
Terraform version: 0.14.8
Provider version: 0.3.1
Kubernetes version: 1.19.6
```

### Affected Resource(s)
`kubernetes_manifest`

### Terraform Configuration Files
You need two files to reproduce this issue, a YAML template and a Terraform HCL file.

`cert-issuer.yaml`
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: ${email_address}
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: tls-acme-account
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: nginx
```
`main.tf`
```hcl
terraform {
  required_version = ">= 0.14.8"

  required_providers {
    kubernetes-alpha = {
      version = ">= 0.3.1"
    }
  }
}

provider "kubernetes-alpha" {
  config_path = "~/.kube/config"
}

resource "kubernetes_manifest" "cert_issuer" {
  provider = kubernetes-alpha

  manifest = yamldecode(templatefile("${path.module}/cert-issuer.yaml", {
    email_address = var.cert_email
  }))
}

variable "cert_email" {
  type = string
}
```

### Debug Output
Debug log: https://gist.github.com/alonsodomin/f561ed8701fdd5785c3400fc351d61eb

### Steps to Reproduce
`terraform plan -var "cert_email=email@example.com"`

### Expected Behavior
Terraform generates a plan in which the actual YAML template file is filled with the variable value passed in and decoded into the HCL structure that represents the Kubernetes manifest.

This works in version 0.2.1 of the provider.

### Actual Behavior
Terraform fails to prepare a plan replacing the variables in the template file. If using a YAML without variables (and the function `file` instead of `templatefile`), the plan is properly generated.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
